### ISSUE TITLE
Tutorial issues 

### ISSUE THREAD

**Issue by waquey** [mit-han-lab/tinyengine#2]
Thanks for the great work! Currently I do not use ArduCam and I just want to test LCD
After following steps described in the tutorial, I can compile without errors but run with some errors: 

(1) No source available for "d_expression_1() at 0x8001058" 

(2) Even if I move lcdsetup() before "SystemClock_Config()" and try to display string on LCD, it doesn't show anything onto the LCD screen. Do we need to set something else? Or is it just related to the cam device? 

(3) Is there any method we can print message in console mode to verify if we enter main() function? 

Furthermore, the table of "Measure results", how can we get the time measurements? Use HAL_getTick() before and after invoke()? 

Could you please help comment that? Thanks

**Comment by RaymondWang0** [comment]
Hi @waquey, thanks for your interest in our work! 
For questions 1 and 2, I believe the errors came out due to the lack of ArduCam. To support your request and also other users who do not have an ArduCam, we will revise our tutorial ASAP to support testing TinyEngine without an ArduCam.
At this time, to test TinyEngine without an ArduCam, you could try to comment out the codes related to camera initialization functions in `main.cpp`. Also, please import a testing image as your input image.
For question 3, if you are using STM32CubeIDE, you can just get into the Debug Mode in the IDE, and use its built-in functions (such as adding breakpoints or using `Run to Line` function). After setting up and starting the debug process in the Debug Mode, you should be able to verify whether you enter `main()` function or not.
For question 4, yes, please use `HAL_GetTick()` before and after `invoke()` to obtain the inference latency.

If you have any further questions, please feel free to let us know!

**Comment by RaymondWang0** [comment]
Hi @waquey, thanks for your interest in our work!
For questions 1 and 2, I believe the errors came out due to the lack of ArduCam. To support your request and also other users who do not have an ArduCam, we will revise our tutorial ASAP to support testing TinyEngine without an ArduCam.
At this time, to test TinyEngine without an ArduCam, you could try to comment out the codes related to camera initialization functions in main.cpp. Also, please import a testing image as your input image.
For question 3, if you are using STM32CubeIDE, you can just get into the Debug Mode in the IDE, and use its built-in functions (such as adding breakpoints or using Run to Line function). After setting up and starting the debug process in the Debug Mode, you should be able to verify whether you enter main() function or not.
For question 4, yes, please use HAL_GetTick() before and after invoke() to obtain the inference latency.

If you have any further questions, please feel free to let us know!

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
